 GM_setValue('percentThreshold_BTCUSD', 97)
  GM_setValue('percentThreshold_ETHUSD', 97)
  GM_setValue('percentThreshold_XRPUSD', 97)
  GM_setValue('percentThreshold_ETCUSD', 97)
  GM_setValue('percentThreshold_ZECUSD', 97)
  GM_setValue('percentThreshold_DASHUSD', 97)
 
  GM_setValue('dynLevelCoef_BTCUSD', 1.99)
  GM_setValue('dynLevelCoef_ETHUSD', 1.79)
  GM_setValue('dynLevelCoef_XRPUSD', 1.74)
  GM_setValue('dynLevelCoef_ETCUSD', 1.74)
  GM_setValue('dynLevelCoef_ZECUSD', 1.99)
  GM_setValue('dynLevelCoef_DASHUSD', 2.09)
 
  GM_setValue('dynLevelSafe_BTCUSD', 57)
  GM_setValue('dynLevelSafe_ETHUSD', 57)
  GM_setValue('dynLevelSafe_XRPUSD', 57)
  GM_setValue('dynLevelSafe_ETCUSD', 57)
  GM_setValue('dynLevelSafe_ZECUSD', 57)
  GM_setValue('dynLevelSafe_DASHUSD', 57)
 
  GM_setValue('diffSafe_BTCUSD', [-100, 100])
  GM_setValue('diffSafe_ETHUSD', [-100, 100])
  GM_setValue('diffSafe_XRPUSD', [-100, 100])
  GM_setValue('diffSafe_ETCUSD', [-100, 100])
  GM_setValue('diffSafe_ZECUSD', [-100, 100])
  GM_setValue('diffSafe_DASHUSD', [-100, 100])
 
  GM_setValue('minDelayBetweenOrdersSec', [65, 225])
  GM_setValue('reloadOnConnectionReset', true)
  GM_setValue('maxBalance', 1501)
  GM_setValue('minBalance', 800)
  GM_setValue('stopLossPercent', 5)
  GM_setValue('maxOpenTrades', 1)
  GM_setValue('minDelayBetweenOrdersSec', 65)
  GM_setValue('orderUpdate', false)
  GM_setValue('orderUpdateRandomFlag', true)
  GM_setValue('orderPercent', 0)
  GM_setValue('orderPercentMin', 1.5)
  GM_setValue('orderPercentMax', 2)
  GM_setValue('orderMax', 7)
  GM_setValue('orderMin', 5)
  GM_setValue('orderRoundCoef', 1)
  GM_setValue('soundON', false)
