 GM_setValue('percentThreshold_BTCUSD', 70)
  GM_setValue('percentThreshold_ETHUSD', 70)
  GM_setValue('percentThreshold_XRPUSD', 75)
  GM_setValue('percentThreshold_ETCUSD', 75)
  GM_setValue('percentThreshold_ZECUSD', 80)
  GM_setValue('percentThreshold_DASHUSD', 80)
 
  GM_setValue('dynLevelCoef_BTCUSD', 1.97)
  GM_setValue('dynLevelCoef_ETHUSD', 1.77)
  GM_setValue('dynLevelCoef_XRPUSD', 1.72)
  GM_setValue('dynLevelCoef_ETCUSD', 1.78)
  GM_setValue('dynLevelCoef_ZECUSD', 1.97)
  GM_setValue('dynLevelCoef_DASHUSD', 2.08)
 
  GM_setValue('dynLevelSafe_BTCUSD', 57)
  GM_setValue('dynLevelSafe_ETHUSD', 57)
  GM_setValue('dynLevelSafe_XRPUSD', 57)
  GM_setValue('dynLevelSafe_ETCUSD', 57)
  GM_setValue('dynLevelSafe_ZECUSD', 57)
  GM_setValue('dynLevelSafe_DASHUSD', 57)
 
  GM_setValue('diffSafe_BTCUSD', [-100, 100])
  GM_setValue('diffSafe_ETHUSD', [-100, 100])
  GM_setValue('diffSafe_XRPUSD', [-100, 100])
  GM_setValue('diffSafe_ETCUSD', [-100, 100])
  GM_setValue('diffSafe_ZECUSD', [-100, 100])
  GM_setValue('diffSafe_DASHUSD', [-100, 100])
 
  GM_setValue('maxBalance', 401)
  GM_setValue('minBalance', 60)
  GM_setValue('stopLossPercent', 5)
  GM_setValue('maxOpenTrades', 1)
  GM_setValue('minDelayBetweenOrdersSec', 65)
  GM_setValue('orderUpdate', true)
  GM_setValue('orderUpdateRandomFlag', true)
  GM_setValue('orderPercent', 0)
  GM_setValue('orderPercentMin', 1.5)
  GM_setValue('orderPercentMax', 2)
  GM_setValue('orderMax', 7)
  GM_setValue('orderMin', 5)
  GM_setValue('orderRoundCoef', 1)
  GM_setValue('soundON', false)
