  GM_setValue('orderSqueezeLimitCur', 0.007)

  GM_setValue('devThresh_AUDCAD', [-0.006, 0.006])
  GM_setValue('devThresh_EURNZD', [-0.006, 0.006])
  GM_setValue('devThresh_EURAUD', [-0.007, 0.007])
  GM_setValue('devThresh_CHFJPY', [-0.006, 0.006])
  GM_setValue('devThresh_USDCHF', [-0.006, 0.006])
  GM_setValue('devThresh_EURUSD', [-0.007, 0.007])
  GM_setValue('devThresh_NZDCAD', [-0.006, 0.006])
  GM_setValue('devThresh_GBPUSD', [-0.007, 0.007])
  GM_setValue('devThresh_AUDCHF', [-0.006, 0.006])
  GM_setValue('devThresh_USDCAD', [-0.006, 0.006])

  GM_setValue('percentThreshold_AUDCAD', 99)
  GM_setValue('percentThreshold_EURNZD', 99)
  GM_setValue('percentThreshold_EURAUD', 99)
  GM_setValue('percentThreshold_CHFJPY', 99)
  GM_setValue('percentThreshold_USDCHF', 99)
  GM_setValue('percentThreshold_EURUSD', 80)
  GM_setValue('percentThreshold_NZDCAD', 99)
  GM_setValue('percentThreshold_GBPUSD', 80)
  GM_setValue('percentThreshold_AUDCHF', 99)
  GM_setValue('percentThreshold_USDCAD', 99)

  GM_setValue('percentThreshold_BTCUSD', 90)
  GM_setValue('percentThreshold_ETHUSD', 90)
  GM_setValue('percentThreshold_XRPUSD', 90)
  GM_setValue('percentThreshold_ETCUSD', 90)
  GM_setValue('percentThreshold_ZECUSD', 90)
  GM_setValue('percentThreshold_DASHUSD', 90)
 
  GM_setValue('dynLevelCoef_BTCUSD', [1.64, 2.1])
  GM_setValue('dynLevelCoef_ETHUSD', [1.9, 2.2])
  GM_setValue('dynLevelCoef_XRPUSD', 1.89)
  GM_setValue('dynLevelCoef_ETCUSD', 1.89)
  GM_setValue('dynLevelCoef_ZECUSD', 1.96)
  GM_setValue('dynLevelCoef_DASHUSD', 1.96)
 
  GM_setValue('dynLevelSafe_BTCUSD', 20)
  GM_setValue('dynLevelSafe_ETHUSD', 60)
  GM_setValue('dynLevelSafe_XRPUSD', 59)
  GM_setValue('dynLevelSafe_ETCUSD', 59)
  GM_setValue('dynLevelSafe_ZECUSD', 59)
  GM_setValue('dynLevelSafe_DASHUSD', 59)

  GM_setValue('reloadOnConnectionReset', true)
  GM_setValue('reloadOnConnectionReset', true)
  GM_setValue('delayLevelToMinOrder', 1.4)
  GM_setValue('delayLevelToStop', 2)
  GM_setValue('orderMinDelay', 1)
  GM_setValue('minDelayBetweenOrdersSecDelay', [7200, 10800 ])
 
  GM_setValue('diffSafe_BTCUSD', [-100, 100])
  GM_setValue('diffSafe_ETHUSD', [-100, 100])
  GM_setValue('diffSafe_XRPUSD', [-100, 100])
  GM_setValue('diffSafe_ETCUSD', [-100, 100])
  GM_setValue('diffSafe_ZECUSD', [-100, 100])
  GM_setValue('diffSafe_DASHUSD', [-100, 100])
  
  GM_setValue('orderSqueezeLimit', 0.08)
  GM_setValue('maxBalance', 505)
  GM_setValue('minBalance', 5)
  GM_setValue('stopLossPercent', 15)
  GM_setValue('maxOpenTrades', 1)
  GM_setValue('minDelayBetweenOrdersSec', [60, 90])
  GM_setValue('orderUpdate', false)
  GM_setValue('orderUpdateRandomFlag', true)
  GM_setValue('orderPercent', 0)
  GM_setValue('orderPercentMin', 7)
  GM_setValue('orderPercentMax', 11)
  GM_setValue('orderMax', 13)
  GM_setValue('orderMin', 10)
  GM_setValue('orderRoundCoef', 1)
  GM_setValue('soundON', false)
  GM_setValue('helperKey', '5PmC7fJ4ykaYqEb9yFjYV_v2')
