  GM_setValue('percentThreshold_BTCUSD', 70)
  GM_setValue('percentThreshold_ETHUSD', 70)
  GM_setValue('percentThreshold_XRPUSD', 75)
  GM_setValue('percentThreshold_ETCUSD', 75)
  GM_setValue('percentThreshold_ZECUSD', 80)
  GM_setValue('percentThreshold_DASHUSD', 80)
 
  GM_setValue('dynLevelCoef_BTCUSD', 1.8)
  GM_setValue('dynLevelCoef_ETHUSD', 1.82)
  GM_setValue('dynLevelCoef_XRPUSD', 1.86)
  GM_setValue('dynLevelCoef_ETCUSD', 1.86)
  GM_setValue('dynLevelCoef_ZECUSD', 1.99)
  GM_setValue('dynLevelCoef_DASHUSD', 1.96)
 
  GM_setValue('dynLevelSafe_BTCUSD', 50)
  GM_setValue('dynLevelSafe_ETHUSD', 55)
  GM_setValue('dynLevelSafe_XRPUSD', 57)
  GM_setValue('dynLevelSafe_ETCUSD', 55)
  GM_setValue('dynLevelSafe_ZECUSD', 58)
  GM_setValue('dynLevelSafe_DASHUSD', 54)
 
  GM_setValue('diffSafe_BTCUSD', [-100, 100])
  GM_setValue('diffSafe_ETHUSD', [-100, 100])
  GM_setValue('diffSafe_XRPUSD', [-100, 100])
  GM_setValue('diffSafe_ETCUSD', [-100, 100])
  GM_setValue('diffSafe_ZECUSD', [-100, 100])
  GM_setValue('diffSafe_DASHUSD', [-100, 100])
 
  GM_setValue('reloadOnConnectionReset', true)
  GM_setValue('minDelayBetweenOrdersSec', [65, 600])
  GM_setValue('reloadOnConnectionReset', true)
  GM_setValue('delayLevelToMinOrder', 1)
  GM_setValue('delayLevelToStop', 2.9)
  GM_setValue('orderMinDelay', 1.2)
  GM_setValue('minDelayBetweenOrdersSecDelay', [7200, 10800 ])

  GM_setValue('maxBalance', 801)
  GM_setValue('minBalance', 50)
  GM_setValue('stopLossPercent', 10)
  GM_setValue('maxOpenTrades', 1)
  GM_setValue('minDelayBetweenOrdersSec', 65)
  GM_setValue('orderUpdate', true)
  GM_setValue('orderUpdateRandomFlag', true)
  GM_setValue('orderPercent', 0)
  GM_setValue('orderPercentMin', 1.5)
  GM_setValue('orderPercentMax', 2)
  GM_setValue('orderMax', 7)
  GM_setValue('orderMin', 5)
  GM_setValue('orderRoundCoef', 1)
  GM_setValue('soundON', false)
