  GM_setValue('percentThreshold_BTCUSD', 70)
  GM_setValue('percentThreshold_ETHUSD', 70)
  GM_setValue('percentThreshold_XRPUSD', 75)
  GM_setValue('percentThreshold_ETCUSD', 75)
  GM_setValue('percentThreshold_ZECUSD', 80)
  GM_setValue('percentThreshold_DASHUSD', 80)
 
  GM_setValue('dynLevelCoef_BTCUSD', 1.89)
  GM_setValue('dynLevelCoef_ETHUSD', 1.88)
  GM_setValue('dynLevelCoef_XRPUSD', 1.89)
  GM_setValue('dynLevelCoef_ETCUSD', 1.89)
  GM_setValue('dynLevelCoef_ZECUSD', 1.96)
  GM_setValue('dynLevelCoef_DASHUSD', 1.96)
 
  GM_setValue('dynLevelSafe_BTCUSD', 50)
  GM_setValue('dynLevelSafe_ETHUSD', 50)
  GM_setValue('dynLevelSafe_XRPUSD', 50)
  GM_setValue('dynLevelSafe_ETCUSD', 50)
  GM_setValue('dynLevelSafe_ZECUSD', 59)
  GM_setValue('dynLevelSafe_DASHUSD', 54)

  GM_setValue('reloadOnConnectionReset', true)
  GM_setValue('minDelayBetweenOrdersSec', [165, 600])
  GM_setValue('reloadOnConnectionReset', true)
  GM_setValue('delayLevelToMinOrder', 1.4)
  GM_setValue('delayLevelToStop', 2)
  GM_setValue('orderMinDelay', 1)
  GM_setValue('minDelayBetweenOrdersSecDelay', [7200, 10800 ])
 
  GM_setValue('diffSafe_BTCUSD', [-100, 100])
  GM_setValue('diffSafe_ETHUSD', [-100, 100])
  GM_setValue('diffSafe_XRPUSD', [-100, 100])
  GM_setValue('diffSafe_ETCUSD', [-100, 100])
  GM_setValue('diffSafe_ZECUSD', [-100, 100])
  GM_setValue('diffSafe_DASHUSD', [-100, 100])
 
  GM_setValue('maxBalance', 355)
  GM_setValue('minBalance', 7)
  GM_setValue('stopLossPercent', 11)
  GM_setValue('maxOpenTrades', 1)
  GM_setValue('minDelayBetweenOrdersSec', 1211)
  GM_setValue('orderUpdate', true)
  GM_setValue('orderUpdateRandomFlag', true)
  GM_setValue('orderPercent', 0)
  GM_setValue('orderPercentMin', 7)
  GM_setValue('orderPercentMax', 10)
  GM_setValue('orderMax', 25)
  GM_setValue('orderMin', 5)
  GM_setValue('orderRoundCoef', 1)
  GM_setValue('soundON', false)
  GM_setValue('helperKey', '5PmC7fJ4ykaYqEb9yFjYV_v2')
